### PR TITLE
Auto-Login Implemented - Add FC Function Support

### PR DESCRIPTION
**Pull request by HHK3**
**General**
- Cleaner Code and more Comments
- Added config_functions.py (with 2 config functions that can be used with discord_rich_presence.py and nso_functions.py)
- Updated the requirements.txt with new Packages 
- Setup.py has a **Upgrade PIP to latest version** function (because Python 3.6.X has a lower PIP version)
- Updated the README.md

**Cookie Generation**
- The user can finally choose between two methods: **Auto-Login Cookie Generation**(Faster) and **Manual Cookie Generation** (Using mitmproxy, safer)
- Fixed a problem when the RP won't start right up after the Cookie has been **manually** retrieved
- Added a link to the Cookie Generation Section (from the Splatnet2Statink Rep.) at the beginning of the code to warn the user before choosing a desired method.

**Friend Code**
- Created a new function where the user can add their Switch FC (after choosing a desired Cookie Generation Method)
- User can also decide to skip this part when they're not feeling it (the RP will show then "FC: Not Given"

**Misc**
- The Video Tutorial will be updated because of these changes. Of course I'll credit you in the vid for making this awesome RP! =)

### CODE REVIEW

**Comment by Wolfy76700** [comment]
Screenshot_25
I'd like to report an error that happened to me when I was trying to run the script (Auto login worked BTW)

**Comment by HHK3** [comment]
Huh, that's a bit weird. Cause I've tested it on 3 different machines (my Laptop, my PC and my Work PC) and functioned normal after running the script. I will take a look how to fix it when I'm back home.

At least thank you for letting me know! And good to hear the Auto-Login works!

**Comment by valknight** [comment]
If this has fixed auto login, then I'm happy to merge this - the other bug is likely something that can be fixed in an upcoming commit.

**Comment by HHK3** [comment]
Ah, I see that Wolfy is using Python 3.7.X. I'm currently using Pyhton 3.6.0 and the script works fine with that. Maybe that could be the problem? (Just a thought)

**Comment by frozenpandaman** [comment]
https://github.com/valknight/Splatnet2-Rich-Presence/blob/1ad92cf70c9c9e676693f1c18a96de52810fa0dc/nso_functions.py#L277

You've essentially taken the entirety of my project's `iksm.py` without asking, but whatever...

I've noticed you're using "splatnet2statink" as your user agent, falsely masquerading as my script both to me and NexusMine's API (which he has presumably not given you permission to use). _This puts **all** projects at risk of being shut down due to unauthorized usage of another user's API._ In addition, unless I missed something, you didn't reach out to me to get permission to send requests to my API and are violating the usage guidelines by 1) not requesting permission or notifying me, which I gladly would have given you; 2) as specified before, not sending a unique user agent.

**Please address this ASAP.**

**Comment by HHK3** [comment]
Thank you for your comment.

First, I want to apologize you for not reaching you out to ask for any Permission and not giving you an unique user agent. A really stupid move of mine.
I'm gonna give your wiki (from your Splatnet2statink) a better read regarding the api, security and privacy. I will also delete my fork just in case.

Again, thank you for addressing this and I'm sorry.
I hope there's a way to undo this merge.

**Comment by valknight** [comment]
The commits has been reversed - if anyone wants to do this without using an API endpoint without permission, that would be rad.

**Comment by frozenpandaman** [comment]
@valknight Sorry for the late reply here! (@HHK3, also saw your Twitter message last night right as I was headed to bed but haven't had a chance to reply yet, but think this should address that as well.)

To both of you, sorry if my comments came off as harsh or drastic. Typed it on mobile too so I was a bit more rushed. I'm 100% fine with you using the s2s API or re-implementing the login/cookie generation code in your script (it is [public](https://github.com/ZekeSnider/NintendoSwitchRESTAPI/blob/master/Splatoon2Blueprint.md) & available in even more detail than combing through my code or docs, after all)! – just that I would appreciate you using a unique user agent so I know what requests are coming from who and all scripts or projects using it are being faithful about their identities… Of course there's no real way to 100% *enforce* this – any number of people could be spoofing s2s or other user agents for whatever reason – but on the basis of good faith, I wanted to just make you aware of the user agent issue as it existed, and to note that I believe it's a benefit to all (including your users) to be transparent about these sorts of API requests, etc. especially as this is all working in a domain not really supported or endorsed by Nintendo. The docs also contain other (hopefully) useful information that I think is good for others – developers and users – to know. Let's work to add this functionality back in to your project, though, as it will definitely benefit users.

I would note that I'd also reach out to NexusMine on Twitter (Google Translate + DM him at the very least?) to ask if you can use his API to generate `f` tokens, given a hash provided by mine (which he gave me instructions on how to do). Where this is coming from is that he's been a little reluctant to even let me use his API in the past – he created it on what he's described as a small, unstable, personal server just for his closed-source app, it has 0 documentation, etc. –and I just fear any increase in requests without notice may make him consider reversing that decision for all other current or potential developers as a whole.

**Comment by frozenpandaman** [comment]
Also (at risk of being sounding a little too anal about this), if you *do* want to directly use the code from my project's `iksm.py` (with credit at the top of the file, please), I'd request that you change this repo's license from MIT to the tiny-bit-more-restrictive GPLv3, which splatnet2statink is licensed under (MIT is compatible with GPL but not vice versa). This ensures the code which is being repurposed in your repo doesn't get used by others in a non-open source manner.

**Comment by HHK3** [comment]
Thank you for the comment, @frozenpandaman . I'm pleased to hear from you that we can add this functionality back into the project, as it will definitely benefit the user. Also, thank you for your explanation about User-Agents. I'll attempt to contact NexusMine on Twitter in the next few days.

In case you don't mind and @valknight is okay with changing the repo's license from MIT to GPLv3, I'd like to use your "Cookie Generation" code from your project's `iksm.py` (I’ll make sure to give credits to you and NexusMine on the top of `nso_functions.py`). I'll also be sure to use a custom User-Agent in the code.

I am also planning to create a video tutorial on how users can set up the Splatoon 2 Rich Presence on their Discord profile. If you and NexusMine (which I’m going to ask as well) want to, I'll credit you two and ValKnight at the beginning of the video and in the description. I will also provide step-by-step instructions on how to generate it automatically and making sure to alert viewers that generating a cookie automatically involves making requests to a non-Nintendo server. In addition, I will also show how it can be done manually using Mitmproxy and the Android emulator Nox.

I hope to hear from you soon. Thank you and have a nice day! =)

**Pull request merged**
